window.onload = function() {
    alert('THIS IS A CLONE, NOT THE ORIGINAL \n "EVERYONE CODES" WEBSITE. \n I DO NOT WORK FOR EVERYONE CODES. \n I DO NOT CLAIM OWNERSHIP OF ANY OF THE ASSETS USED. \n THIS WEBSITE EXISTS PURELY FOR PRACTICE OF MY HTML/CSS SKILLS ');
};