window.onload = function() {
    alert('THIS IS A CLONE, NOT THE ORIGINAL "EVERYONE CODES" WEBSITE. I DO NOT WORK FOR EVERYONE CODES. I DO NOT CLAIM OWNERSHIP OF ANY OF THE ASSETS USED. THIS WEBSITE EXISTS PURELY FOR PRACTICE OF MY HTML/CSS SKILLS ');
};